global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'task3-enterprise'
    static_configs:
      - targets: ['task3-enterprise:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']

  - job_name: 'task3-health'
    static_configs:
      - targets: ['task3-enterprise:8080']
    metrics_path: '/health'
    scrape_interval: 30s