// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/campaigns": {
    params: {};
  };
  "/campaigns/:id": {
    params: {
      "id": string;
    };
  };
  "/campaigns/:id/edit": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/campaigns" | "/campaigns/:id" | "/campaigns/:id/edit";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/campaigns.tsx": {
    id: "routes/campaigns";
    page: "/campaigns" | "/campaigns/:id" | "/campaigns/:id/edit";
  };
  "./routes/campaigns._index.tsx": {
    id: "routes/campaigns._index";
    page: "/campaigns";
  };
  "./routes/campaigns.$id.tsx": {
    id: "routes/campaigns.$id";
    page: "/campaigns/:id";
  };
  "./routes/campaigns.$id.edit.tsx": {
    id: "routes/campaigns.$id.edit";
    page: "/campaigns/:id/edit";
  };
};